version: "3"
services:

  web:
    image: paberlo/p2gps23:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
      restart_policy:
        condition: none
    ports:
      - "80:8080"  

  mongo:
    image: paberlo/p2gps23:db
    deploy:
      replicas: 1  
      resources:
        limits:
          cpus: "0.15"
      restart_policy:
        condition: none
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - "db-data:/data/db" 

  order:
    image: paberlo/p2gps23:order
    depends_on:
      - "mongo" 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
      restart_policy:
        condition: none
    ports:
      - "8080"

volumes: 
   db-data: