name: CI solamente

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 #descarga el repositorio en el ejecutor

      - name: Set up JDK 8
        uses: actions/setup-java@v3 
        with:
            java-version: '8'
            distribution: 'adopt'
            server-id: github 
            settings-path: ${{ github.workspace }} # location for the settings.xml file
  
        #### BUILDS ######
      #- uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      
      #- uses: gradle/gradle-build-action@v1
      #  with:
      #    gradle-version: 2.1
      
      - uses: gradle/gradle-build-action@v2
        with:
         #gradle-version: 2.1
         configuration-cache: false
        
      - name: build del Front
        working-directory: src/Clients
        run: ./gradlew build --no-build-cache
      - uses: actions/upload-artifact@v3 #guarda en Artifacts el resultado del build. opcional.
        with:
           name: Clients
           path: src/Clients/build/libs
    
      - name: build del Back
        working-directory: src/Backend/OrderService
        run: ./gradlew build test
